kind: pipeline
name: default

steps:
  - name: build-wasm
    image: drailing/godot-export-container
    commands:
      - cd web
      - Godot_v3.2.3-stable_linux_headless.64 project.godot --export "HTML5" ../deploy/client/game/web.html

  - name: build-webserver
    image: drailing/go_packr_zip
    environment:
      GO111MODULE: on
    commands:
      - cd deploy
      - cd client
      - go build -o webserver

  - name: dockerize-client
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: drailing/dino-poker-client
      dockerfile: deploy/client/Dockerfile
      context: deploy/client
      tags:
        - "${DRONE_TAG=latest}"
    when:
      event:
        - tag

  - name: prepare-server
    image: drailing/godot-export-container
    commands:
      - cp /bin/Godot_v3.2.3-stable_linux_headless.64 ./
    when:
      event:
        - tag

  - name: dockerize-server
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: drailing/dino-poker-server
      tags:
        - "${DRONE_TAG=latest}"
    when:
      event:
        - tag
